#' Plot Offset Polygons
#'
#' Plot the offset polygons generated by the `generate_offset_polygon` function.
#'
#' @param offset_polygons Default `NULL`. A list of data frames, where each data frame represents an offset polygon. Each data frame should have 'x' and 'y' columns representing coordinates.
#' @param skeleton Default `NULL`. The straight skeleton used to generate the offset polygon. Include this if you want to adjust the plot
#' range to encompass the entire original polygon.
#' @param border Default `grDevices::heat.colors`.  A color or palette function to generate the color palette for the offset polygons' borders.
#' @param xlim Default `NULL`. The x-axis limits as a vector of two values (min, max). If `NULL`, it calculates the limits from the data.
#' @param ylim Default `NULL`. The y-axis limits as a vector of two values (min, max). If `NULL`, it calculates the limits from the data.
#' @param color Default `NULL`. A color or palette function to generate the fill palette for the polygons' interiors.
#' @param linewidth Default `1`. The linewidth of the polygon.
#' @param plot_original_polygon Default `TRUE`. If `skeleton` passed as well, plots the original polygon.
#'
#' @return A plot showing the offset polygons.
#' @export
#' @examples
#' # Outer polygon
#' vertices = matrix(c(0,0, 7,0, 7,7, 0,7, 0,0), ncol = 2, byrow = TRUE)
#' # Holes inside the polygon
#' hole_1 = matrix(c(1,1, 2,1, 2,2, 1,2, 1,1), ncol = 2, byrow = TRUE)[5:1,]
#' hole_2 = matrix(c(5,5, 6,5, 6,6, 5,6, 5,5), ncol = 2, byrow = TRUE)[5:1,]
#' skeleton = skeletonize(vertices, holes = list(hole_1, hole_2))
#' plot_skeleton(skeleton)
#'
#' #Generate three offsets
#' plot_offset_polygon(generate_offset_polygon(skeleton, c(0.25,0.75,1.5,2)))
#'
#' #Generate three offsets, including the original polygon
#' plot_offset_polygon(generate_offset_polygon(skeleton, c(0.25,0.75,1.5,2)), skeleton = skeleton)
#'
#' #Generate many offsets
#' plot_offset_polygon(generate_offset_polygon(skeleton, seq(0,2.5,by=0.1)))
#'
#' # Skeletonize and plot an {sf} object
#' if(length(find.package("spData",quiet = TRUE)) > 0) {
#'   us_states = spData::us_states
#'   texas = us_states[us_states$NAME == "Texas",]
#'   texas_skeleton = skeletonize(texas)
#'   plot_offset_polygon(generate_offset_polygon(texas_skeleton, seq(0, 2.5, by = 0.1)),
#'                       border = heat.colors,
#'                       linewidth = 1)
#' }
plot_offset_polygon = function(offset_polygons, skeleton = NULL,
                               plot_original_polygon = TRUE,
                               color = NULL, border= "dodgerblue", xlim=NULL, ylim=NULL,
                               linewidth = 1) {
  # Check if ggplot2 package is installed
  if(!(length(find.package("ggplot2", quiet = TRUE)) > 0)) {
    stop("{ggplot2} package required for plot_offset_polygon_ggplot()")
  }

  # Import ggplot2 functions
  ggplot = ggplot2::ggplot
  aes = ggplot2::aes
  geom_polygon = ggplot2::geom_polygon
  theme_void = ggplot2::theme_void
  coord_fixed = ggplot2::coord_fixed
  x = y = NULL
  # Set color palettes if provided
  n_polygons = length(offset_polygons)
  if(is.function(border)) {
    border = border(n_polygons)
  } else if (is.character(border)) {
    if(length(border) == 1) {
      border = rep(border[1], n_polygons)
    }
  }
  if(is.function(color)) {
    color = color(n_polygons)
  } else if (is.character(border)) {
    if(length(color) == 1) {
      color = rep(color[1], n_polygons)
    }
  }

  # Create an empty ggplot object
  p = ggplot() + theme_void()

  # If skeleton is provided, calculate xlim and ylim based on skeleton
  if (!is.null(skeleton)) {
    # p = plot_skeleton(skeleton)

    original_vertices = attr(skeleton, "original_vertices")
    colnames(original_vertices) = c("x","y")
    # xlim_vals = range(original_vertices[, 1])
    # ylim_vals = range(original_vertices[, 2])
  } else {
    p = ggplot() + theme_void() + coord_fixed()
  }

  # Add offset polygons to the plot
  for(i in seq_len(n_polygons)) {
    poly = offset_polygons[[i]]
    colnames(poly) = c("x","y")
    p = p + geom_polygon(data = data.frame(poly), aes(x = x, y = y),
                         fill = NA, color = border[i], size = linewidth)
  }

  # If skeleton is provided and plot_original_polygon is TRUE, add original polygon and holes to the plot
  if (!is.null(skeleton) && plot_original_polygon) {
    p = p + geom_polygon(data = data.frame(original_vertices),
                         aes(x = x, y = y), fill = NA, color = "black", size = linewidth)

    # Plot holes, if they exist
    original_holes = attr(skeleton, "original_holes")
    if (!is.null(original_holes)) {
      for (hole in original_holes) {
        colnames(hole) = c("x","y")

        p = p + geom_polygon(data = data.frame(hole),
                             aes(x = x, y = y), fill = NA, color = "black", size = linewidth)
      }
    }
  }

  # Set x and y limits if provided
  p = p + coord_fixed()
  # }
  # if(!is.null(ylim)) {
  #   p = p + coord_cartesian(ylim = ylim)
  # }

  # Return the plot
  return(p)
}
