#' Plot Offset Polygons
#'
#' Plot the offset polygons generated by the `generate_offset_polygon` function.
#'
#' @param offset_polygons Default `NULL`. A list of data frames, where each data frame represents an offset polygon. Each data frame should have 'x' and 'y' columns representing coordinates.
#' @param skeleton Default `NULL`. The straight skeleton used to generate the offset polygon. Include this if you want to adjust the plot
#' range to encompass the entire original polygon.
#' @param main Default "Offset Polygons". The main title for the plot.
#' @param col Default "lightblue". The fill color for the polygons. This argument is ignored if `palette_col` is provided.
#' @param border Default "blue". The border color for the polygons. This argument is ignored if `palette_border` is provided.
#' @param xlim Default `NULL`. The x-axis limits as a vector of two values (min, max). If `NULL`, it calculates the limits from the data.
#' @param ylim Default `NULL`. The y-axis limits as a vector of two values (min, max). If `NULL`, it calculates the limits from the data.
#' @param add Default `FALSE`. A logical indicating whether to add the offset polygons to an existing plot (`TRUE`) or create a new one (`FALSE`).
#' @param palette_col Default `NULL`. A function to generate the color palette for the polygons' interiors. This function should accept the number of polygons as input and return a vector of colors. If provided, it overrides the `col` argument.
#' @param palette_border Default `NULL`. A function to generate the color palette for the polygons' borders . This function should accept the number of polygons as input and return a vector of colors. If provided, it overrides the `border` argument.
#' @param linewidth Default `1`. The linewidth of the polygon.
#'
#' @return A plot showing the offset polygons.
#' @export
#' @examples
#' # Outer polygon
#' vertices = matrix(c(0,0, 7,0, 7,7, 0,7, 0,0), ncol = 2, byrow = TRUE)
#' # Holes inside the polygon
#' hole_1 = matrix(c(1,1, 2,1, 2,2, 1,2, 1,1), ncol = 2, byrow = TRUE)[5:1,]
#' hole_2 = matrix(c(5,5, 6,5, 6,6, 5,6, 5,5), ncol = 2, byrow = TRUE)[5:1,]
#' skeleton = skeletonize(vertices, holes = list(hole_1, hole_2))
#' plot_skeleton(skeleton)
#' plot_offset_polygon(generate_offset_polygon(skeleton, seq(0,2.5,by=0.1)), add = TRUE)
#' # Now with colors
#' plot_offset_polygon(generate_offset_polygon(skeleton, seq(0,2.5,by=0.1)),
#'                     palette_border = terrain.colors, skeleton = skeleton,
#'                     linewidth = 3)
#'
#' # Skeletonize and plot an {sf} object
#' if(length(find.package("spData",quiet = TRUE)) > 0) {
#'   us_states = spData::us_states
#'   texas = us_states[us_states$NAME == "Texas",]
#'   texas_skeleton = skeletonize(texas)
#'   plot_offset_polygon(generate_offset_polygon(texas_skeleton, seq(0, 2.5, by = 0.1)),
#'                       palette_border = heat.colors, skeleton = texas_skeleton,
#'                       linewidth = 2)
#' }
plot_offset_polygon = function(offset_polygons, skeleton = NULL, main="Offset Polygons",
                               plot_original_polygon = TRUE,
                               col = NA, border="blue", xlim=NULL, ylim=NULL, add=FALSE,
                               palette_border = NULL, palette_col = NULL, linewidth = 1) {
  n_polygons = length(offset_polygons)
  if(!is.null(skeleton)) {
    xlim = c(0,1)
    ylim = c(0,1)

    min_x = min(skeleton$nodes$x) - 1
    min_y = min(skeleton$nodes$y) - 1
    max_x = max(skeleton$nodes$x) + 1
    max_y = max(skeleton$nodes$y) + 1

    span_x = max_x - min_x
    span_y = max_y - min_y

    xlim_vals = c(min_x + span_x * xlim[1], min_x + span_x * xlim[2])
    ylim_vals = c(min_y + span_y * ylim[1], min_y + span_y * ylim[2])
  } else {
    xlim_vals = xlim
    ylim_vals = ylim
  }
  if (!is.null(palette_border)) {
    generated_colors_border = palette_border(n_polygons)
    border = generated_colors_border
  }
  if (!is.null(palette_col)) {
    generated_colors_col = palette_col(n_polygons)
    col = generated_colors_col
  }

  if(length(border) == 1) {
    border = rep(border, n_polygons)
  }
  if(length(col) == 1) {
    col = rep(col, n_polygons)
  }

  # If not adding to an existing plot, set up the new plot
  if(!add) {
    if(is.null(xlim)) {
      xlim = range(sapply(offset_polygons, function(poly) range(poly$x)))
    }
    if(is.null(ylim)) {
      ylim = range(sapply(offset_polygons, function(poly) range(poly$y)))
    }

    plot(1, 1, type="n", xlab="", ylab="", xlim=xlim_vals, ylim=ylim_vals,
         main=main, xaxs="i", yaxs="i",
         axes=FALSE, ann=FALSE, asp = 1)
  }
  if (!is.null(skeleton) && plot_original_polygon) {
    # Plot the main outer polygon
    original_vertices = attr(skeleton, "original_vertices")
    polygon(original_vertices[,1], original_vertices[,2], col=NA, border="black", lwd=linewidth)

    # Plot holes, if they exist
    original_holes = attr(skeleton, "original_holes")
    if (!is.null(original_holes)) {
      for (hole in original_holes) {
        polygon(hole[,1], hole[,2], col=NA, border="black", lwd=linewidth)
      }
    }
  }

  # Plot each offset polygon
  for(i in seq_len(n_polygons)) {
    poly = offset_polygons[[i]]
    polygon(poly$x, poly$y, col=col[i], border=border[i], lwd = linewidth)
  }
}
