# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_ccw_polygon <- function(vertices) {
    .Call(`_rayskeleton_is_ccw_polygon`, vertices)
}

is_simple_polygon <- function(vertices) {
    .Call(`_rayskeleton_is_simple_polygon`, vertices)
}

skeletonize_rcpp <- function(vertices, holes, offset) {
    .Call(`_rayskeleton_skeletonize_rcpp`, vertices, holes, offset)
}

