# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convert_ss_to_polygons_rcpp <- function(ss, numbercores) {
    .Call(`_rayskeleton_convert_ss_to_polygons_rcpp`, ss, numbercores)
}

generate_offset_links_nodes_rcpp <- function(ss_links, ss_nodes, offsets, return_polys = FALSE, progress = FALSE) {
    .Call(`_rayskeleton_generate_offset_links_nodes_rcpp`, ss_links, ss_nodes, offsets, return_polys, progress)
}

is_ccw_polygon <- function(vertices) {
    .Call(`_rayskeleton_is_ccw_polygon`, vertices)
}

is_simple_polygon <- function(vertices) {
    .Call(`_rayskeleton_is_simple_polygon`, vertices)
}

skeletonize_rcpp <- function(vertices, holes, offset) {
    .Call(`_rayskeleton_skeletonize_rcpp`, vertices, holes, offset)
}

